class CreateShops < ActiveRecord::Migration[5.2]
  def change
    create_table :shops do |t|
      t.string :storeName
      t.string :storeNumber
      t.integer :store_id
      t.integer :user_id
      t.datetime :shopDate
      t.datetime :shopTime
      t.string :shopType
      t.string :shiftManager
      t.string :upFront
      t.string :mgrAppearance
      t.string :headset
      t.string :crewAppearance
      t.string :r2d2Charts
      t.string :rdm
      t.string :kiosks
      t.string :tableService
      t.string :tableTent
      t.string :shiftMgrComment
      t.string :fastComment
      t.string :qualityComment
      t.string :accuracyComment
      t.string :hospitalityComment
      t.string :cleanComment
      t.string :foodSafetyComment
      t.string :itemsOrdered
      t.string :waitTime
      t.string :responseTime
      t.string :presentTime
      t.string :oepTime
      t.string :totalTime
      t.string :pullForward
      t.string :pullForwardTime
      t.string :numberCars
      t.string :tandem
      t.string :fcWaitTime
      t.string :fcDeliveryTIme
      t.string :fcTotalTime
      t.string :numberGuests
      t.string :popcornFull
      t.string :completeOrder
      t.string :condiment
      t.string :condimentBag
      t.string :readerboard
      t.string :marketing
      t.string :dtCommentNumber
      t.string :presell
      t.string :upsell
      t.string :otName
      t.string :cashierName
      t.string :presenterName
      t.string :pullForwardPresenterName
      t.string :repeatOrderAsk
      t.string :cashierGreeting
      t.string :cashierAsk
      t.string :presenterGreet
      t.string :presenterTell
      t.string :pfTell
      t.string :fresh
      t.string :friesGood
      t.string :drinkGood
      t.string :codClean
      t.string :dtClean
      t.string :lotClean
      t.string :corralClean
      t.string :lidsClosed
      t.string :dtGlassClean
      t.string :windowsClean
      t.string :trashFull
      t.string :commentSignVisible
      t.string :floorClean
      t.string :tableClean
      t.string :drinkClean
      t.string :popCornClean
      t.string :ventsClean
      t.string :sanitizer
      t.string :tvOn
      t.string :restroomClean
      t.string :insideTrash
      t.string :crewRoom
      t.string :uhcTimer
      t.string :prepTimer
      t.string :bunTimer
      t.string :tenderCorrect
      t.string :tenderDate
      t.string :tenderTime
      t.string :qtrCorrect
      t.string :qtrDate
      t.string :qtrTime
      t.string :glove
      t.string :pieTimer
      t.string :saladTimer
      t.string :shopper
      t.string :supervisor
      t.string :opsManager
      t.string :possiblePoints
      t.string :unscoredPoints
      t.string :achievedPoints
      t.string :score
      t.timestamps
    end
  end
end
